/**
 * Copyright (c) Microsoft.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

/*

Generated Command List:

azure operating-system list 


azure operating-system list-families 



*/

'use strict';
var profile = require('../../../util/profile');
var utils = require('../../../util/utils');

var $ = utils.getLocaleString;exports.init = function (cli) {

/*
  OperatingSystem List
*/
  var operatingSystemList = cli.category('compute').description('Commands to invoke service management operations.').category('operating-system')
  .description($('Commands to manage your operating system.  '));
  operatingSystemList.command('list')
  .description($('The List Operating Systems operation lists the versions of the guest operating system that are currently available in Windows Azure. The 2010-10-28 version of List Operating Systems also indicates what family an operating system version belongs to. Currently Azure supports two operating system families: the Azure guest operating system that is substantially compatible with Windows Server 2008 SP2, and the Azure guest operating system that is substantially compatible with Windows Server 2008 R2.  (see http://msdn.microsoft.com/en-us/library/windowsazure/ff684168.aspx for more information)'))
  .usage('[options]')
  .option('-s, --subscription <subscription>', $('The subscription identifier'))
  .execute(function(options, _) {
    var subscription = profile.current.getSubscription(options.subscription);
    var computeManagementClient = utils.createComputeClient(subscription);
    var result = computeManagementClient.operatingSystems.list(_);
    if (result) {
      cli.output.json(result);
    }
  });
/*
  OperatingSystem ListFamilies
*/
  var operatingSystemListFamilies = cli.category('compute').description('Commands to invoke service management operations.').category('operating-system')
  .description($('Commands to manage your operating system.  '));
  operatingSystemListFamilies.command('list-families')
  .description($('The List OS Families operation lists the guest operating system families available in Azure, and also lists the operating system versions available for each family. Currently Azure supports two operating system families: the Azure guest operating system that is substantially compatible with Windows Server 2008 SP2, and the Azure guest operating system that is substantially compatible with Windows Server 2008 R2.  (see http://msdn.microsoft.com/en-us/library/windowsazure/gg441291.aspx for more information)'))
  .usage('[options]')
  .option('-s, --subscription <subscription>', $('The subscription identifier'))
  .execute(function(options, _) {
    var subscription = profile.current.getSubscription(options.subscription);
    var computeManagementClient = utils.createComputeClient(subscription);
    var result = computeManagementClient.operatingSystems.listFamilies(_);
    if (result) {
      cli.output.json(result);
    }
  });


};
