/**
 * Copyright (c) Microsoft.  All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Warning: This code was generated by a tool.
// 
// Changes to this file may cause incorrect behavior and will be lost if the
// code is regenerated.

/*

Generated Command List:

azure virtual-machine-extension list 


azure virtual-machine-extension list-versions 
--publisher-name $p0
--name $p1


*/

'use strict';
var profile = require('../../../util/profile');
var utils = require('../../../util/utils');

var $ = utils.getLocaleString;exports.init = function (cli) {

/*
  VirtualMachineExtension List
*/
  var virtualMachineExtensionList = cli.category('compute').description('Commands to invoke service management operations.').category('virtual-machine-extension')
  .description($('Commands to manage your virtual machine extension.  '));
  virtualMachineExtensionList.command('list')
  .description($('The List Resource Extensions operation lists the resource extensions that are available to add to a Virtual Machine. In Azure, a process can run as a resource extension of a Virtual Machine. For example, Remote Desktop Access or the Azure Diagnostics Agent can run as resource extensions to the Virtual Machine.  (see http://msdn.microsoft.com/en-us/library/windowsazure/dn495441.aspx for more information)'))
  .usage('[options]')
  .option('-s, --subscription <subscription>', $('The subscription identifier'))
  .execute(function(options, _) {
    var subscription = profile.current.getSubscription(options.subscription);
    var computeManagementClient = utils.createComputeClient(subscription);
    var result = computeManagementClient.virtualMachineExtensions.list(_);
    if (result) {
      cli.output.json(result);
    }
  });
/*
  VirtualMachineExtension ListVersions
  --publisher-name
  --name
*/
  var virtualMachineExtensionListVersions = cli.category('compute').description('Commands to invoke service management operations.').category('virtual-machine-extension')
  .description($('Commands to manage your virtual machine extension.  '));
  virtualMachineExtensionListVersions.command('list-versions [publisher-name] [name]')
  .description($('The List Resource Extension Versions operation lists the versions of a resource extension that are available to add to a Virtual Machine. In Azure, a process can run as a resource extension of a Virtual Machine. For example, Remote Desktop Access or the Azure Diagnostics Agent can run as resource extensions to the Virtual Machine.  (see http://msdn.microsoft.com/en-us/library/windowsazure/dn495440.aspx for more information)'))
  .usage('[options] <publisher-name> <name>')
  .option('--publisher-name <publisher-name>', $('publisher-name'))
  .option('-n, --name <name>', $('name'))
  .option('-s, --subscription <subscription>', $('The subscription identifier'))
  .execute(function(publisherName, name, options, _) {
    if (!publisherName) {
      publisherName = cli.interaction.promptIfNotGiven($('publisher-name : '), publisherName, _);
    }

    cli.output.verbose('publisherName = ' + publisherName);
    if (!name) {
      name = cli.interaction.promptIfNotGiven($('name : '), name, _);
    }

    cli.output.verbose('name = ' + name);
    var subscription = profile.current.getSubscription(options.subscription);
    var computeManagementClient = utils.createComputeClient(subscription);
    var result = computeManagementClient.virtualMachineExtensions.listVersions(publisherName, name, _);
    if (result) {
      cli.output.json(result);
    }
  });


};
