// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://login.microsoftonline.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0', '*')
  .reply(400, "{\"error\":\"invalid_request\",\"error_description\":\"AADSTS90014: The request body must contain the following parameter: 'refresh_token'.\\r\\nTrace ID: c15d06cb-3c8d-4080-95eb-b7ae55ea7e79\\r\\nCorrelation ID: d50ed51b-4dfc-46cd-bbd1-475375b25852\\r\\nTimestamp: 2016-01-16 04:36:28Z\",\"error_codes\":[90014],\"timestamp\":\"2016-01-16 04:36:28Z\",\"trace_id\":\"c15d06cb-3c8d-4080-95eb-b7ae55ea7e79\",\"correlation_id\":\"d50ed51b-4dfc-46cd-bbd1-475375b25852\"}", { 'cache-control': 'no-cache, no-store',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-request-id': 'c15d06cb-3c8d-4080-95eb-b7ae55ea7e79',
  'client-request-id': 'd50ed51b-4dfc-46cd-bbd1-475375b25852',
  'x-ms-gateway-service-instanceid': 'ESTSFE_IN_372',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  p3p: 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'set-cookie': 
   [ 'flight-uxoptin=true; path=/; secure; HttpOnly',
     'x-ms-gateway-slice=productionb; path=/; secure; HttpOnly',
     'stsservicecookie=ests; path=/; secure; HttpOnly' ],
  'x-powered-by': 'ASP.NET',
  date: 'Sat, 16 Jan 2016 04:36:27 GMT',
  connection: 'close',
  'content-length': '438' });
 return result; },
function (nock) { 
var result = 
nock('https://login.microsoftonline.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0', '*')
  .reply(400, "{\"error\":\"invalid_request\",\"error_description\":\"AADSTS90014: The request body must contain the following parameter: 'refresh_token'.\\r\\nTrace ID: c15d06cb-3c8d-4080-95eb-b7ae55ea7e79\\r\\nCorrelation ID: d50ed51b-4dfc-46cd-bbd1-475375b25852\\r\\nTimestamp: 2016-01-16 04:36:28Z\",\"error_codes\":[90014],\"timestamp\":\"2016-01-16 04:36:28Z\",\"trace_id\":\"c15d06cb-3c8d-4080-95eb-b7ae55ea7e79\",\"correlation_id\":\"d50ed51b-4dfc-46cd-bbd1-475375b25852\"}", { 'cache-control': 'no-cache, no-store',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-request-id': 'c15d06cb-3c8d-4080-95eb-b7ae55ea7e79',
  'client-request-id': 'd50ed51b-4dfc-46cd-bbd1-475375b25852',
  'x-ms-gateway-service-instanceid': 'ESTSFE_IN_372',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  p3p: 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'set-cookie': 
   [ 'flight-uxoptin=true; path=/; secure; HttpOnly',
     'x-ms-gateway-slice=productionb; path=/; secure; HttpOnly',
     'stsservicecookie=ests; path=/; secure; HttpOnly' ],
  'x-powered-by': 'ASP.NET',
  date: 'Sat, 16 Jan 2016 04:36:27 GMT',
  connection: 'close',
  'content-length': '438' });
 return result; },
function (nock) { 
var result = 
nock('http://login.microsoftonline.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0', '*')
  .reply(200, "{\"token_type\":\"Bearer\",\"expires_in\":\"3599\",\"expires_on\":\"1452922588\",\"not_before\":\"1452918688\",\"resource\":\"https://management.core.windows.net/\",\"access_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNDUyOTE4Njg4LCJuYmYiOjE0NTI5MTg2ODgsImV4cCI6MTQ1MjkyMjU4OCwiYXBwaWQiOiIzNGIzYjgxYy1hOGFkLTQ4YzEtODY3MC04Yjk2ZjUzYmVmODkiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwib2lkIjoiMmY5YTc0MGYtNzllMi00MjVlLThmN2MtZTRmYWVkNzBiNWE4Iiwic3ViIjoiMmY5YTc0MGYtNzllMi00MjVlLThmN2MtZTRmYWVkNzBiNWE4IiwidGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3IiwidmVyIjoiMS4wIn0.p1lohLFm4g9Yl3DV7yWucH2ekP_yVHtejo7SOpB-xmez8BVcrlGiqlyfjqVVJS4DW4w1EZgyzlEbmJ-2wu3YNjll51x-s95QOp8KxNNgstGylQGQSxeQR1yTFtzwQJYdNbSc2ctggwtyO4fTBuXnkbMhcUBf5GLaOggu_XofkEVUV-my2BbpZQdhscXyLFn-RycXZVWhtJQJ5Arr2AkxYnXOMDfQZBVtjjvcuyzosFiAkJi9tebPr8s5Dpp9wUCGRcPKaf1Lzr8GbQDdKJAvb4yJvH3IgXl5yRB8fRDMS5OnV931R-yuC_77vK-A62isMmfqnmdeNn-HYx4Ctp-mDQ\"}", { 'cache-control': 'no-cache, no-store',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-request-id': '98499905-d4b0-4682-b2fb-0beb8b7a75ef',
  'client-request-id': 'd50ed51b-4dfc-46cd-bbd1-475375b25852',
  'x-ms-gateway-service-instanceid': 'ESTSFE_IN_187',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  p3p: 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'set-cookie': 
   [ 'flight-uxoptin=true; path=/; secure; HttpOnly',
     'x-ms-gateway-slice=productionb; path=/; secure; HttpOnly',
     'stsservicecookie=ests; path=/; secure; HttpOnly' ],
  'x-powered-by': 'ASP.NET',
  date: 'Sat, 16 Jan 2016 04:36:28 GMT',
  connection: 'close',
  'content-length': '1234' });
 return result; },
function (nock) { 
var result = 
nock('https://login.microsoftonline.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/72f988bf-86f1-41af-91ab-2d7cd011db47/oauth2/token?api-version=1.0', '*')
  .reply(200, "{\"token_type\":\"Bearer\",\"expires_in\":\"3599\",\"expires_on\":\"1452922588\",\"not_before\":\"1452918688\",\"resource\":\"https://management.core.windows.net/\",\"access_token\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSIsImtpZCI6Ik1uQ19WWmNBVGZNNXBPWWlKSE1iYTlnb0VLWSJ9.eyJhdWQiOiJodHRwczovL21hbmFnZW1lbnQuY29yZS53aW5kb3dzLm5ldC8iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwiaWF0IjoxNDUyOTE4Njg4LCJuYmYiOjE0NTI5MTg2ODgsImV4cCI6MTQ1MjkyMjU4OCwiYXBwaWQiOiIzNGIzYjgxYy1hOGFkLTQ4YzEtODY3MC04Yjk2ZjUzYmVmODkiLCJhcHBpZGFjciI6IjEiLCJpZHAiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC83MmY5ODhiZi04NmYxLTQxYWYtOTFhYi0yZDdjZDAxMWRiNDcvIiwib2lkIjoiMmY5YTc0MGYtNzllMi00MjVlLThmN2MtZTRmYWVkNzBiNWE4Iiwic3ViIjoiMmY5YTc0MGYtNzllMi00MjVlLThmN2MtZTRmYWVkNzBiNWE4IiwidGlkIjoiNzJmOTg4YmYtODZmMS00MWFmLTkxYWItMmQ3Y2QwMTFkYjQ3IiwidmVyIjoiMS4wIn0.p1lohLFm4g9Yl3DV7yWucH2ekP_yVHtejo7SOpB-xmez8BVcrlGiqlyfjqVVJS4DW4w1EZgyzlEbmJ-2wu3YNjll51x-s95QOp8KxNNgstGylQGQSxeQR1yTFtzwQJYdNbSc2ctggwtyO4fTBuXnkbMhcUBf5GLaOggu_XofkEVUV-my2BbpZQdhscXyLFn-RycXZVWhtJQJ5Arr2AkxYnXOMDfQZBVtjjvcuyzosFiAkJi9tebPr8s5Dpp9wUCGRcPKaf1Lzr8GbQDdKJAvb4yJvH3IgXl5yRB8fRDMS5OnV931R-yuC_77vK-A62isMmfqnmdeNn-HYx4Ctp-mDQ\"}", { 'cache-control': 'no-cache, no-store',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  server: 'Microsoft-IIS/8.5',
  'x-ms-request-id': '98499905-d4b0-4682-b2fb-0beb8b7a75ef',
  'client-request-id': 'd50ed51b-4dfc-46cd-bbd1-475375b25852',
  'x-ms-gateway-service-instanceid': 'ESTSFE_IN_187',
  'x-content-type-options': 'nosniff',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  p3p: 'CP="DSP CUR OTPi IND OTRi ONL FIN"',
  'set-cookie': 
   [ 'flight-uxoptin=true; path=/; secure; HttpOnly',
     'x-ms-gateway-slice=productionb; path=/; secure; HttpOnly',
     'stsservicecookie=ests; path=/; secure; HttpOnly' ],
  'x-powered-by': 'ASP.NET',
  date: 'Sat, 16 Jan 2016 04:36:28 GMT',
  connection: 'close',
  'content-length': '1234' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate5940?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xplatTstVmssGCreate5940' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-request-id': '8690d398-0fa2-4aac-a12e-0be1363e239b',
  'x-ms-correlation-request-id': '8690d398-0fa2-4aac-a12e-0be1363e239b',
  'x-ms-routing-request-id': 'WESTUS:20160116T043628Z:8690d398-0fa2-4aac-a12e-0be1363e239b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:36:28 GMT',
  connection: 'close',
  'content-length': '115' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate5940?api-version=2014-04-01-preview')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xplatTstVmssGCreate5940' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-request-id': '8690d398-0fa2-4aac-a12e-0be1363e239b',
  'x-ms-correlation-request-id': '8690d398-0fa2-4aac-a12e-0be1363e239b',
  'x-ms-routing-request-id': 'WESTUS:20160116T043628Z:8690d398-0fa2-4aac-a12e-0be1363e239b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:36:28 GMT',
  connection: 'close',
  'content-length': '115' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate5940?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940\",\"name\":\"xplatTstVmssGCreate5940\",\"location\":\"southeastasia\",\"tags\":{\"arm-cli-vmss-parameter-create-tests\":\"2016-01-16T04:36:27.551Z\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '280',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': '5895d182-2729-46d0-bff4-dd2025b9c42e',
  'x-ms-correlation-request-id': '5895d182-2729-46d0-bff4-dd2025b9c42e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043632Z:5895d182-2729-46d0-bff4-dd2025b9c42e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:36:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate5940?api-version=2014-04-01-preview', '*')
  .reply(201, "{\"id\":\"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940\",\"name\":\"xplatTstVmssGCreate5940\",\"location\":\"southeastasia\",\"tags\":{\"arm-cli-vmss-parameter-create-tests\":\"2016-01-16T04:36:27.551Z\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '280',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': '5895d182-2729-46d0-bff4-dd2025b9c42e',
  'x-ms-correlation-request-id': '5895d182-2729-46d0-bff4-dd2025b9c42e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043632Z:5895d182-2729-46d0-bff4-dd2025b9c42e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:36:31 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Storage/storageAccounts/xplatteststorage16792?api-version=2015-06-15', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/2a6ed24c-fc6c-4f43-96ac-f2469b0a3cb3?monitor=true&api-version=2015-06-15',
  'retry-after': '25',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': 'd681f74e-b1d6-424b-a407-553c95d08f1e',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': 'd681f74e-b1d6-424b-a407-553c95d08f1e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043636Z:d681f74e-b1d6-424b-a407-553c95d08f1e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:36:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Storage/storageAccounts/xplatteststorage16792?api-version=2015-06-15', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/2a6ed24c-fc6c-4f43-96ac-f2469b0a3cb3?monitor=true&api-version=2015-06-15',
  'retry-after': '25',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': 'd681f74e-b1d6-424b-a407-553c95d08f1e',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': 'd681f74e-b1d6-424b-a407-553c95d08f1e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043636Z:d681f74e-b1d6-424b-a407-553c95d08f1e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:36:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/2a6ed24c-fc6c-4f43-96ac-f2469b0a3cb3?monitor=true&api-version=2015-06-15')
  .reply(200, "{\"location\":\"southeastasia\",\"properties\":{\"accountType\":\"Standard_GRS\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '72',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '879aa515-888d-4ad9-a1a8-6fa24827d010',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '879aa515-888d-4ad9-a1a8-6fa24827d010',
  'x-ms-routing-request-id': 'WESTUS:20160116T043701Z:879aa515-888d-4ad9-a1a8-6fa24827d010',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:37:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/2a6ed24c-fc6c-4f43-96ac-f2469b0a3cb3?monitor=true&api-version=2015-06-15')
  .reply(200, "{\"location\":\"southeastasia\",\"properties\":{\"accountType\":\"Standard_GRS\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '72',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': '879aa515-888d-4ad9-a1a8-6fa24827d010',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '879aa515-888d-4ad9-a1a8-6fa24827d010',
  'x-ms-routing-request-id': 'WESTUS:20160116T043701Z:879aa515-888d-4ad9-a1a8-6fa24827d010',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:37:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/virtualNetworks/xplattestvnet8039' under resource group 'xplatTstVmssGCreate5940' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'dea12c76-29e5-460b-b481-3bbf3ce85ebf',
  'x-ms-correlation-request-id': 'dea12c76-29e5-460b-b481-3bbf3ce85ebf',
  'x-ms-routing-request-id': 'WESTUS:20160116T043703Z:dea12c76-29e5-460b-b481-3bbf3ce85ebf',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:37:02 GMT',
  connection: 'close',
  'content-length': '178' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/virtualNetworks/xplattestvnet8039' under resource group 'xplatTstVmssGCreate5940' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'dea12c76-29e5-460b-b481-3bbf3ce85ebf',
  'x-ms-correlation-request-id': 'dea12c76-29e5-460b-b481-3bbf3ce85ebf',
  'x-ms-routing-request-id': 'WESTUS:20160116T043703Z:dea12c76-29e5-460b-b481-3bbf3ce85ebf',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:37:02 GMT',
  connection: 'close',
  'content-length': '178' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestvnet8039\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039\",\r\n  \"etag\": \"W/\\\"e601ad53-8d97-458e-b8d3-6289758c9ec7\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"resourceGuid\": \"aa984bf3-8ae4-41c5-b5b8-70939f247431\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '625',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': 'fb78759f-9892-432e-8397-4247b0f8cb5a',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/fb78759f-9892-432e-8397-4247b0f8cb5a?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': '2367686a-3ed0-4583-bfa5-28045cfe966e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043707Z:2367686a-3ed0-4583-bfa5-28045cfe966e',
  date: 'Sat, 16 Jan 2016 04:37:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestvnet8039\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039\",\r\n  \"etag\": \"W/\\\"e601ad53-8d97-458e-b8d3-6289758c9ec7\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"resourceGuid\": \"aa984bf3-8ae4-41c5-b5b8-70939f247431\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '625',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': 'fb78759f-9892-432e-8397-4247b0f8cb5a',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/fb78759f-9892-432e-8397-4247b0f8cb5a?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': '2367686a-3ed0-4583-bfa5-28045cfe966e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043707Z:2367686a-3ed0-4583-bfa5-28045cfe966e',
  date: 'Sat, 16 Jan 2016 04:37:06 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/fb78759f-9892-432e-8397-4247b0f8cb5a?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '859fae38-42c3-4e81-ae1f-0ec426f00858',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '2f861a9d-b588-48b0-9285-4e25e839f21a',
  'x-ms-routing-request-id': 'WESTUS:20160116T043718Z:2f861a9d-b588-48b0-9285-4e25e839f21a',
  date: 'Sat, 16 Jan 2016 04:37:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/fb78759f-9892-432e-8397-4247b0f8cb5a?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '859fae38-42c3-4e81-ae1f-0ec426f00858',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '2f861a9d-b588-48b0-9285-4e25e839f21a',
  'x-ms-routing-request-id': 'WESTUS:20160116T043718Z:2f861a9d-b588-48b0-9285-4e25e839f21a',
  date: 'Sat, 16 Jan 2016 04:37:18 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet8039\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039\",\r\n  \"etag\": \"W/\\\"000b68eb-9531-4166-acd2-c0ea13788d84\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"aa984bf3-8ae4-41c5-b5b8-70939f247431\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"000b68eb-9531-4166-acd2-c0ea13788d84"',
  'x-ms-request-id': 'f248e592-95eb-4d21-878e-c1c07c5ed6b3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '31ca163e-1c2b-4cec-9ea8-5f2661803de8',
  'x-ms-routing-request-id': 'WESTUS:20160116T043719Z:31ca163e-1c2b-4cec-9ea8-5f2661803de8',
  date: 'Sat, 16 Jan 2016 04:37:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet8039\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039\",\r\n  \"etag\": \"W/\\\"000b68eb-9531-4166-acd2-c0ea13788d84\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"aa984bf3-8ae4-41c5-b5b8-70939f247431\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"000b68eb-9531-4166-acd2-c0ea13788d84"',
  'x-ms-request-id': 'f248e592-95eb-4d21-878e-c1c07c5ed6b3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '31ca163e-1c2b-4cec-9ea8-5f2661803de8',
  'x-ms-routing-request-id': 'WESTUS:20160116T043719Z:31ca163e-1c2b-4cec-9ea8-5f2661803de8',
  date: 'Sat, 16 Jan 2016 04:37:19 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet8039\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039\",\r\n  \"etag\": \"W/\\\"000b68eb-9531-4166-acd2-c0ea13788d84\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"aa984bf3-8ae4-41c5-b5b8-70939f247431\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"000b68eb-9531-4166-acd2-c0ea13788d84"',
  'x-ms-request-id': 'ec9c22d0-341f-4f05-b56e-f3368ade2528',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': 'da6c984c-0e3c-42d5-b5f1-9a818da412c0',
  'x-ms-routing-request-id': 'WESTUS:20160116T043721Z:da6c984c-0e3c-42d5-b5f1-9a818da412c0',
  date: 'Sat, 16 Jan 2016 04:37:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet8039\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039\",\r\n  \"etag\": \"W/\\\"000b68eb-9531-4166-acd2-c0ea13788d84\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"aa984bf3-8ae4-41c5-b5b8-70939f247431\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"000b68eb-9531-4166-acd2-c0ea13788d84"',
  'x-ms-request-id': 'ec9c22d0-341f-4f05-b56e-f3368ade2528',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': 'da6c984c-0e3c-42d5-b5f1-9a818da412c0',
  'x-ms-routing-request-id': 'WESTUS:20160116T043721Z:da6c984c-0e3c-42d5-b5f1-9a818da412c0',
  date: 'Sat, 16 Jan 2016 04:37:20 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15')
  .reply(404, "{\r\n  \"error\": {\r\n    \"code\": \"NotFound\",\r\n    \"message\": \"Resource /subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785 not found.\",\r\n    \"details\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '287',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'bc8d0d3b-b4f1-4e8d-8a9c-f6f5d9546fe7',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '26689351-731b-4618-b279-0ddc67e0047a',
  'x-ms-routing-request-id': 'WESTUS:20160116T043722Z:26689351-731b-4618-b279-0ddc67e0047a',
  date: 'Sat, 16 Jan 2016 04:37:21 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15')
  .reply(404, "{\r\n  \"error\": {\r\n    \"code\": \"NotFound\",\r\n    \"message\": \"Resource /subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785 not found.\",\r\n    \"details\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '287',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'bc8d0d3b-b4f1-4e8d-8a9c-f6f5d9546fe7',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': '26689351-731b-4618-b279-0ddc67e0047a',
  'x-ms-routing-request-id': 'WESTUS:20160116T043722Z:26689351-731b-4618-b279-0ddc67e0047a',
  date: 'Sat, 16 Jan 2016 04:37:21 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestsubnet8785\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\",\r\n  \"etag\": \"W/\\\"268f4595-6878-4d57-ad88-12a8b2d419e6\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '386',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '97527ff3-140e-41c5-a1b8-055d3eb13689',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/97527ff3-140e-41c5-a1b8-055d3eb13689?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': 'bcd2683d-9311-4d5d-965f-3e28b226963c',
  'x-ms-routing-request-id': 'WESTUS:20160116T043723Z:bcd2683d-9311-4d5d-965f-3e28b226963c',
  date: 'Sat, 16 Jan 2016 04:37:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestsubnet8785\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\",\r\n  \"etag\": \"W/\\\"268f4595-6878-4d57-ad88-12a8b2d419e6\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '386',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '97527ff3-140e-41c5-a1b8-055d3eb13689',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/97527ff3-140e-41c5-a1b8-055d3eb13689?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': 'bcd2683d-9311-4d5d-965f-3e28b226963c',
  'x-ms-routing-request-id': 'WESTUS:20160116T043723Z:bcd2683d-9311-4d5d-965f-3e28b226963c',
  date: 'Sat, 16 Jan 2016 04:37:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/97527ff3-140e-41c5-a1b8-055d3eb13689?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'b7287f17-5d08-4f8e-9b6c-664c4490f334',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': 'feb58484-aab4-42c6-8995-ccf0d10b844e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043734Z:feb58484-aab4-42c6-8995-ccf0d10b844e',
  date: 'Sat, 16 Jan 2016 04:37:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/97527ff3-140e-41c5-a1b8-055d3eb13689?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'b7287f17-5d08-4f8e-9b6c-664c4490f334',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': 'feb58484-aab4-42c6-8995-ccf0d10b844e',
  'x-ms-routing-request-id': 'WESTUS:20160116T043734Z:feb58484-aab4-42c6-8995-ccf0d10b844e',
  date: 'Sat, 16 Jan 2016 04:37:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet8785\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\",\r\n  \"etag\": \"W/\\\"11097ed9-c375-4aa1-8b60-3fbd04918bf4\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"11097ed9-c375-4aa1-8b60-3fbd04918bf4"',
  'x-ms-request-id': 'ed404476-fdb7-42cc-82d7-cfd2633ced63',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'fe5a3099-c8fc-466d-a796-e4e64f420265',
  'x-ms-routing-request-id': 'WESTUS:20160116T043735Z:fe5a3099-c8fc-466d-a796-e4e64f420265',
  date: 'Sat, 16 Jan 2016 04:37:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet8785\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\",\r\n  \"etag\": \"W/\\\"11097ed9-c375-4aa1-8b60-3fbd04918bf4\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"11097ed9-c375-4aa1-8b60-3fbd04918bf4"',
  'x-ms-request-id': 'ed404476-fdb7-42cc-82d7-cfd2633ced63',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14998',
  'x-ms-correlation-request-id': 'fe5a3099-c8fc-466d-a796-e4e64f420265',
  'x-ms-routing-request-id': 'WESTUS:20160116T043735Z:fe5a3099-c8fc-466d-a796-e4e64f420265',
  date: 'Sat, 16 Jan 2016 04:37:34 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet8785\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\",\r\n  \"etag\": \"W/\\\"11097ed9-c375-4aa1-8b60-3fbd04918bf4\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"11097ed9-c375-4aa1-8b60-3fbd04918bf4"',
  'x-ms-request-id': 'bbe43f6d-b4fd-433b-a7e4-1cd08354dd09',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '381b99fd-72ea-41b7-8fce-404a19c7cd7a',
  'x-ms-routing-request-id': 'WESTUS:20160116T043736Z:381b99fd-72ea-41b7-8fce-404a19c7cd7a',
  date: 'Sat, 16 Jan 2016 04:37:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualnetworks/xplattestvnet8039/subnets/xplattestsubnet8785?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet8785\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\",\r\n  \"etag\": \"W/\\\"11097ed9-c375-4aa1-8b60-3fbd04918bf4\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"11097ed9-c375-4aa1-8b60-3fbd04918bf4"',
  'x-ms-request-id': 'bbe43f6d-b4fd-433b-a7e4-1cd08354dd09',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '381b99fd-72ea-41b7-8fce-404a19c7cd7a',
  'x-ms-routing-request-id': 'WESTUS:20160116T043736Z:381b99fd-72ea-41b7-8fce-404a19c7cd7a',
  date: 'Sat, 16 Jan 2016 04:37:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/networkInterfaces/xplattestnic6420' under resource group 'xplatTstVmssGCreate5940' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '04f268a5-b721-4ce2-89e2-ddfa7e0f43d8',
  'x-ms-correlation-request-id': '04f268a5-b721-4ce2-89e2-ddfa7e0f43d8',
  'x-ms-routing-request-id': 'WESTUS:20160116T043737Z:04f268a5-b721-4ce2-89e2-ddfa7e0f43d8',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:37:37 GMT',
  connection: 'close',
  'content-length': '179' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/networkInterfaces/xplattestnic6420' under resource group 'xplatTstVmssGCreate5940' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '04f268a5-b721-4ce2-89e2-ddfa7e0f43d8',
  'x-ms-correlation-request-id': '04f268a5-b721-4ce2-89e2-ddfa7e0f43d8',
  'x-ms-routing-request-id': 'WESTUS:20160116T043737Z:04f268a5-b721-4ce2-89e2-ddfa7e0f43d8',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Sat, 16 Jan 2016 04:37:37 GMT',
  connection: 'close',
  'content-length': '179' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestnic6420\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420\",\r\n  \"etag\": \"W/\\\"9b9a8e6e-f49f-4f31-96ea-ddd5fad03f3c\\\"\",\r\n  \"type\": \"Microsoft.Network/networkInterfaces\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"323a9bac-43a0-4a65-9544-98174e6b2dee\",\r\n    \"ipConfigurations\": [\r\n      {\r\n        \"name\": \"Nic-IP-config\",\r\n        \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420/ipConfigurations/Nic-IP-config\",\r\n        \"etag\": \"W/\\\"9b9a8e6e-f49f-4f31-96ea-ddd5fad03f3c\\\"\",\r\n        \"properties\": {\r\n          \"provisioningState\": \"Succeeded\",\r\n          \"privateIPAddress\": \"10.0.0.4\",\r\n          \"privateIPAllocationMethod\": \"Dynamic\",\r\n          \"subnet\": {\r\n            \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\"\r\n          },\r\n          \"primary\": true\r\n        }\r\n      }\r\n    ],\r\n    \"dnsSettings\": {\r\n      \"dnsServers\": [],\r\n      \"appliedDnsServers\": []\r\n    },\r\n    \"enableIPForwarding\": false\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1377',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '6af6daf3-3410-40fe-9bc2-a3491b883479',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/6af6daf3-3410-40fe-9bc2-a3491b883479?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '93123973-6ec5-4bac-8cec-f2174b51faf7',
  'x-ms-routing-request-id': 'WESTUS:20160116T043742Z:93123973-6ec5-4bac-8cec-f2174b51faf7',
  date: 'Sat, 16 Jan 2016 04:37:41 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestnic6420\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420\",\r\n  \"etag\": \"W/\\\"9b9a8e6e-f49f-4f31-96ea-ddd5fad03f3c\\\"\",\r\n  \"type\": \"Microsoft.Network/networkInterfaces\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"323a9bac-43a0-4a65-9544-98174e6b2dee\",\r\n    \"ipConfigurations\": [\r\n      {\r\n        \"name\": \"Nic-IP-config\",\r\n        \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/networkInterfaces/xplattestnic6420/ipConfigurations/Nic-IP-config\",\r\n        \"etag\": \"W/\\\"9b9a8e6e-f49f-4f31-96ea-ddd5fad03f3c\\\"\",\r\n        \"properties\": {\r\n          \"provisioningState\": \"Succeeded\",\r\n          \"privateIPAddress\": \"10.0.0.4\",\r\n          \"privateIPAllocationMethod\": \"Dynamic\",\r\n          \"subnet\": {\r\n            \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate5940/providers/Microsoft.Network/virtualNetworks/xplattestvnet8039/subnets/xplattestsubnet8785\"\r\n          },\r\n          \"primary\": true\r\n        }\r\n      }\r\n    ],\r\n    \"dnsSettings\": {\r\n      \"dnsServers\": [],\r\n      \"appliedDnsServers\": []\r\n    },\r\n    \"enableIPForwarding\": false\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1377',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '6af6daf3-3410-40fe-9bc2-a3491b883479',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/6af6daf3-3410-40fe-9bc2-a3491b883479?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '93123973-6ec5-4bac-8cec-f2174b51faf7',
  'x-ms-routing-request-id': 'WESTUS:20160116T043742Z:93123973-6ec5-4bac-8cec-f2174b51faf7',
  date: 'Sat, 16 Jan 2016 04:37:41 GMT',
  connection: 'close' });
 return result; }]];