// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate7800?api-version=2015-11-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xplatTstVmssGCreate7800' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14975',
  'x-ms-request-id': '5f1c68dc-16be-4e5e-907f-6be5d325a291',
  'x-ms-correlation-request-id': '5f1c68dc-16be-4e5e-907f-6be5d325a291',
  'x-ms-routing-request-id': 'CENTRALUS:20160204T171227Z:5f1c68dc-16be-4e5e-907f-6be5d325a291',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:12:26 GMT',
  connection: 'close',
  'content-length': '115' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate7800?api-version=2015-11-01')
  .reply(404, "{\"error\":{\"code\":\"ResourceGroupNotFound\",\"message\":\"Resource group 'xplatTstVmssGCreate7800' could not be found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-ratelimit-remaining-subscription-reads': '14975',
  'x-ms-request-id': '5f1c68dc-16be-4e5e-907f-6be5d325a291',
  'x-ms-correlation-request-id': '5f1c68dc-16be-4e5e-907f-6be5d325a291',
  'x-ms-routing-request-id': 'CENTRALUS:20160204T171227Z:5f1c68dc-16be-4e5e-907f-6be5d325a291',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:12:26 GMT',
  connection: 'close',
  'content-length': '115' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate7800?api-version=2015-11-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800\",\"name\":\"xplatTstVmssGCreate7800\",\"location\":\"southeastasia\",\"tags\":{\"arm-cli-vmss-parameter-create-tests\":\"2016-02-04T17:12:25.691Z\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '280',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-request-id': '4b4f9378-fa48-489c-bea7-a49421b30488',
  'x-ms-correlation-request-id': '4b4f9378-fa48-489c-bea7-a49421b30488',
  'x-ms-routing-request-id': 'CENTRALUS:20160204T171230Z:4b4f9378-fa48-489c-bea7-a49421b30488',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:12:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourcegroups/xplatTstVmssGCreate7800?api-version=2015-11-01', '*')
  .reply(201, "{\"id\":\"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800\",\"name\":\"xplatTstVmssGCreate7800\",\"location\":\"southeastasia\",\"tags\":{\"arm-cli-vmss-parameter-create-tests\":\"2016-02-04T17:12:25.691Z\"},\"properties\":{\"provisioningState\":\"Succeeded\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '280',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-request-id': '4b4f9378-fa48-489c-bea7-a49421b30488',
  'x-ms-correlation-request-id': '4b4f9378-fa48-489c-bea7-a49421b30488',
  'x-ms-routing-request-id': 'CENTRALUS:20160204T171230Z:4b4f9378-fa48-489c-bea7-a49421b30488',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:12:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Storage/storageAccounts/xplatteststorage17972?api-version=2015-06-15', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/74fb26fd-75e1-4bcd-b7b4-cd2063de3458?monitor=true&api-version=2015-06-15',
  'retry-after': '25',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': 'ab6fbc9d-1d68-4c98-816f-a663da83a491',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': 'ab6fbc9d-1d68-4c98-816f-a663da83a491',
  'x-ms-routing-request-id': 'CENTRALUS:20160204T171236Z:ab6fbc9d-1d68-4c98-816f-a663da83a491',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:12:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Storage/storageAccounts/xplatteststorage17972?api-version=2015-06-15', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/74fb26fd-75e1-4bcd-b7b4-cd2063de3458?monitor=true&api-version=2015-06-15',
  'retry-after': '25',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-request-id': 'ab6fbc9d-1d68-4c98-816f-a663da83a491',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-correlation-request-id': 'ab6fbc9d-1d68-4c98-816f-a663da83a491',
  'x-ms-routing-request-id': 'CENTRALUS:20160204T171236Z:ab6fbc9d-1d68-4c98-816f-a663da83a491',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:12:36 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/74fb26fd-75e1-4bcd-b7b4-cd2063de3458?monitor=true&api-version=2015-06-15')
  .reply(200, "{\"properties\":{\"accountType\":\"Standard_GRS\"},\"location\":\"southeastasia\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '72',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': 'f554a9ec-e155-4566-a70c-1dcc2b7f6e24',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': 'f554a9ec-e155-4566-a70c-1dcc2b7f6e24',
  'x-ms-routing-request-id': 'WESTUS:20160204T171308Z:f554a9ec-e155-4566-a70c-1dcc2b7f6e24',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:13:08 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Storage/operations/74fb26fd-75e1-4bcd-b7b4-cd2063de3458?monitor=true&api-version=2015-06-15')
  .reply(200, "{\"properties\":{\"accountType\":\"Standard_GRS\"},\"location\":\"southeastasia\"}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '72',
  'content-type': 'application/json',
  expires: '-1',
  'x-ms-request-id': 'f554a9ec-e155-4566-a70c-1dcc2b7f6e24',
  server: 'Microsoft-Azure-Storage-Resource-Provider/1.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': 'f554a9ec-e155-4566-a70c-1dcc2b7f6e24',
  'x-ms-routing-request-id': 'WESTUS:20160204T171308Z:f554a9ec-e155-4566-a70c-1dcc2b7f6e24',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:13:08 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/virtualNetworks/xplattestvnet5443' under resource group 'xplatTstVmssGCreate7800' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '47f64ed5-07cc-40ca-8eaf-c292afcc47ec',
  'x-ms-correlation-request-id': '47f64ed5-07cc-40ca-8eaf-c292afcc47ec',
  'x-ms-routing-request-id': 'WESTUS:20160204T171310Z:47f64ed5-07cc-40ca-8eaf-c292afcc47ec',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:13:10 GMT',
  connection: 'close',
  'content-length': '178' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/virtualNetworks/xplattestvnet5443' under resource group 'xplatTstVmssGCreate7800' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '47f64ed5-07cc-40ca-8eaf-c292afcc47ec',
  'x-ms-correlation-request-id': '47f64ed5-07cc-40ca-8eaf-c292afcc47ec',
  'x-ms-routing-request-id': 'WESTUS:20160204T171310Z:47f64ed5-07cc-40ca-8eaf-c292afcc47ec',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:13:10 GMT',
  connection: 'close',
  'content-length': '178' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestvnet5443\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443\",\r\n  \"etag\": \"W/\\\"cba7c9f3-6968-4b9a-9d35-9740eb9b712e\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"resourceGuid\": \"e7227374-1d5a-44ec-9b14-fdcced2997cb\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '625',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '6dc16db1-f722-45bf-85e8-faea6c9e877d',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/6dc16db1-f722-45bf-85e8-faea6c9e877d?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1188',
  'x-ms-correlation-request-id': 'be0b5723-d39d-4b4e-b7fb-556941809a2f',
  'x-ms-routing-request-id': 'WESTUS:20160204T171316Z:be0b5723-d39d-4b4e-b7fb-556941809a2f',
  date: 'Thu, 04 Feb 2016 17:13:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestvnet5443\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443\",\r\n  \"etag\": \"W/\\\"cba7c9f3-6968-4b9a-9d35-9740eb9b712e\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"resourceGuid\": \"e7227374-1d5a-44ec-9b14-fdcced2997cb\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '625',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '6dc16db1-f722-45bf-85e8-faea6c9e877d',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/6dc16db1-f722-45bf-85e8-faea6c9e877d?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1188',
  'x-ms-correlation-request-id': 'be0b5723-d39d-4b4e-b7fb-556941809a2f',
  'x-ms-routing-request-id': 'WESTUS:20160204T171316Z:be0b5723-d39d-4b4e-b7fb-556941809a2f',
  date: 'Thu, 04 Feb 2016 17:13:16 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/6dc16db1-f722-45bf-85e8-faea6c9e877d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'da0c008c-85f5-4b3e-a436-b39b18aa228b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': '3cf1fe81-1792-48b7-8dc1-36a310df4679',
  'x-ms-routing-request-id': 'WESTUS:20160204T171347Z:3cf1fe81-1792-48b7-8dc1-36a310df4679',
  date: 'Thu, 04 Feb 2016 17:13:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/6dc16db1-f722-45bf-85e8-faea6c9e877d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'da0c008c-85f5-4b3e-a436-b39b18aa228b',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14997',
  'x-ms-correlation-request-id': '3cf1fe81-1792-48b7-8dc1-36a310df4679',
  'x-ms-routing-request-id': 'WESTUS:20160204T171347Z:3cf1fe81-1792-48b7-8dc1-36a310df4679',
  date: 'Thu, 04 Feb 2016 17:13:46 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet5443\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443\",\r\n  \"etag\": \"W/\\\"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"e7227374-1d5a-44ec-9b14-fdcced2997cb\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc"',
  'x-ms-request-id': 'e1a85790-898c-45af-b102-488d48339c94',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '327448a5-59d0-4c7b-bc90-961777015301',
  'x-ms-routing-request-id': 'WESTUS:20160204T171348Z:327448a5-59d0-4c7b-bc90-961777015301',
  date: 'Thu, 04 Feb 2016 17:13:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet5443\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443\",\r\n  \"etag\": \"W/\\\"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"e7227374-1d5a-44ec-9b14-fdcced2997cb\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc"',
  'x-ms-request-id': 'e1a85790-898c-45af-b102-488d48339c94',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '327448a5-59d0-4c7b-bc90-961777015301',
  'x-ms-routing-request-id': 'WESTUS:20160204T171348Z:327448a5-59d0-4c7b-bc90-961777015301',
  date: 'Thu, 04 Feb 2016 17:13:48 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet5443\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443\",\r\n  \"etag\": \"W/\\\"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"e7227374-1d5a-44ec-9b14-fdcced2997cb\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc"',
  'x-ms-request-id': 'ae4c6c47-8208-472b-b9c6-6ac1daa1efea',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '6cf2b548-4548-461c-af7f-21e0c5509cc4',
  'x-ms-routing-request-id': 'WESTUS:20160204T171350Z:6cf2b548-4548-461c-af7f-21e0c5509cc4',
  date: 'Thu, 04 Feb 2016 17:13:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestvnet5443\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443\",\r\n  \"etag\": \"W/\\\"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc\\\"\",\r\n  \"type\": \"Microsoft.Network/virtualNetworks\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"e7227374-1d5a-44ec-9b14-fdcced2997cb\",\r\n    \"addressSpace\": {\r\n      \"addressPrefixes\": [\r\n        \"10.0.0.0/16\"\r\n      ]\r\n    },\r\n    \"dhcpOptions\": {\r\n      \"dnsServers\": []\r\n    },\r\n    \"subnets\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '626',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"2cf0a909-0fc7-4f91-acd5-20d5b8d37cfc"',
  'x-ms-request-id': 'ae4c6c47-8208-472b-b9c6-6ac1daa1efea',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14999',
  'x-ms-correlation-request-id': '6cf2b548-4548-461c-af7f-21e0c5509cc4',
  'x-ms-routing-request-id': 'WESTUS:20160204T171350Z:6cf2b548-4548-461c-af7f-21e0c5509cc4',
  date: 'Thu, 04 Feb 2016 17:13:50 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15')
  .reply(404, "{\r\n  \"error\": {\r\n    \"code\": \"NotFound\",\r\n    \"message\": \"Resource /subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005 not found.\",\r\n    \"details\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '287',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'af1a79c9-2946-4bf2-a53b-67687d9a3b0d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14949',
  'x-ms-correlation-request-id': '94a49b30-d1a9-4ee9-9114-bbc91b516861',
  'x-ms-routing-request-id': 'WESTUS:20160204T171352Z:94a49b30-d1a9-4ee9-9114-bbc91b516861',
  date: 'Thu, 04 Feb 2016 17:13:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15')
  .reply(404, "{\r\n  \"error\": {\r\n    \"code\": \"NotFound\",\r\n    \"message\": \"Resource /subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005 not found.\",\r\n    \"details\": []\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '287',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': 'af1a79c9-2946-4bf2-a53b-67687d9a3b0d',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14949',
  'x-ms-correlation-request-id': '94a49b30-d1a9-4ee9-9114-bbc91b516861',
  'x-ms-routing-request-id': 'WESTUS:20160204T171352Z:94a49b30-d1a9-4ee9-9114-bbc91b516861',
  date: 'Thu, 04 Feb 2016 17:13:51 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestsubnet3005\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\",\r\n  \"etag\": \"W/\\\"78e86a8e-ae7f-43bc-a0d5-ed9c1cf2a363\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '386',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '05544202-ad3c-4298-b8cf-1af4163c3aaa',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/05544202-ad3c-4298-b8cf-1af4163c3aaa?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '84570e99-ccff-4eae-8007-9559dea93a2b',
  'x-ms-routing-request-id': 'WESTUS:20160204T171353Z:84570e99-ccff-4eae-8007-9559dea93a2b',
  date: 'Thu, 04 Feb 2016 17:13:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestsubnet3005\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\",\r\n  \"etag\": \"W/\\\"78e86a8e-ae7f-43bc-a0d5-ed9c1cf2a363\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Updating\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '386',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'retry-after': '10',
  'x-ms-request-id': '05544202-ad3c-4298-b8cf-1af4163c3aaa',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/05544202-ad3c-4298-b8cf-1af4163c3aaa?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1199',
  'x-ms-correlation-request-id': '84570e99-ccff-4eae-8007-9559dea93a2b',
  'x-ms-routing-request-id': 'WESTUS:20160204T171353Z:84570e99-ccff-4eae-8007-9559dea93a2b',
  date: 'Thu, 04 Feb 2016 17:13:53 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/05544202-ad3c-4298-b8cf-1af4163c3aaa?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '1158845e-d8e1-444a-9afe-d2f2111998b3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14970',
  'x-ms-correlation-request-id': '7e0c643e-fc8a-4dd0-be85-a1d49ad37fe0',
  'x-ms-routing-request-id': 'WESTUS:20160204T171424Z:7e0c643e-fc8a-4dd0-be85-a1d49ad37fe0',
  date: 'Thu, 04 Feb 2016 17:14:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/05544202-ad3c-4298-b8cf-1af4163c3aaa?api-version=2015-06-15')
  .reply(200, "{\r\n  \"status\": \"Succeeded\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '29',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '1158845e-d8e1-444a-9afe-d2f2111998b3',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14970',
  'x-ms-correlation-request-id': '7e0c643e-fc8a-4dd0-be85-a1d49ad37fe0',
  'x-ms-routing-request-id': 'WESTUS:20160204T171424Z:7e0c643e-fc8a-4dd0-be85-a1d49ad37fe0',
  date: 'Thu, 04 Feb 2016 17:14:24 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet3005\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\",\r\n  \"etag\": \"W/\\\"8c147b4f-c9a4-4982-8559-2d02f58ad7f0\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"8c147b4f-c9a4-4982-8559-2d02f58ad7f0"',
  'x-ms-request-id': '76fa904b-4f8e-4885-9330-3d8044ff2562',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '0bbc1815-524d-4f51-9fa3-9827f7c8cb15',
  'x-ms-routing-request-id': 'WESTUS:20160204T171426Z:0bbc1815-524d-4f51-9fa3-9827f7c8cb15',
  date: 'Thu, 04 Feb 2016 17:14:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet3005\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\",\r\n  \"etag\": \"W/\\\"8c147b4f-c9a4-4982-8559-2d02f58ad7f0\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"8c147b4f-c9a4-4982-8559-2d02f58ad7f0"',
  'x-ms-request-id': '76fa904b-4f8e-4885-9330-3d8044ff2562',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '0bbc1815-524d-4f51-9fa3-9827f7c8cb15',
  'x-ms-routing-request-id': 'WESTUS:20160204T171426Z:0bbc1815-524d-4f51-9fa3-9827f7c8cb15',
  date: 'Thu, 04 Feb 2016 17:14:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet3005\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\",\r\n  \"etag\": \"W/\\\"8c147b4f-c9a4-4982-8559-2d02f58ad7f0\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"8c147b4f-c9a4-4982-8559-2d02f58ad7f0"',
  'x-ms-request-id': 'bceef824-3762-40ff-8180-7527b7fe067e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '95ef911f-0bfa-4f52-abfa-2fe1010f4fb4',
  'x-ms-routing-request-id': 'WESTUS:20160204T171427Z:95ef911f-0bfa-4f52-abfa-2fe1010f4fb4',
  date: 'Thu, 04 Feb 2016 17:14:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualnetworks/xplattestvnet5443/subnets/xplattestsubnet3005?api-version=2015-06-15')
  .reply(200, "{\r\n  \"name\": \"xplattestsubnet3005\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\",\r\n  \"etag\": \"W/\\\"8c147b4f-c9a4-4982-8559-2d02f58ad7f0\\\"\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"addressPrefix\": \"10.0.0.0/24\"\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '387',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  etag: 'W/"8c147b4f-c9a4-4982-8559-2d02f58ad7f0"',
  'x-ms-request-id': 'bceef824-3762-40ff-8180-7527b7fe067e',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14996',
  'x-ms-correlation-request-id': '95ef911f-0bfa-4f52-abfa-2fe1010f4fb4',
  'x-ms-routing-request-id': 'WESTUS:20160204T171427Z:95ef911f-0bfa-4f52-abfa-2fe1010f4fb4',
  date: 'Thu, 04 Feb 2016 17:14:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/networkInterfaces/xplattestnic3796' under resource group 'xplatTstVmssGCreate7800' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'f2cc5888-4bee-4546-8c6c-c69e997028ee',
  'x-ms-correlation-request-id': 'f2cc5888-4bee-4546-8c6c-c69e997028ee',
  'x-ms-routing-request-id': 'WESTUS:20160204T171427Z:f2cc5888-4bee-4546-8c6c-c69e997028ee',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:14:27 GMT',
  connection: 'close',
  'content-length': '179' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Network/networkInterfaces/xplattestnic3796' under resource group 'xplatTstVmssGCreate7800' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': 'f2cc5888-4bee-4546-8c6c-c69e997028ee',
  'x-ms-correlation-request-id': 'f2cc5888-4bee-4546-8c6c-c69e997028ee',
  'x-ms-routing-request-id': 'WESTUS:20160204T171427Z:f2cc5888-4bee-4546-8c6c-c69e997028ee',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Thu, 04 Feb 2016 17:14:27 GMT',
  connection: 'close',
  'content-length': '179' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestnic3796\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796\",\r\n  \"etag\": \"W/\\\"2d8db33a-1a2a-4248-8733-761f96f9ea19\\\"\",\r\n  \"type\": \"Microsoft.Network/networkInterfaces\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"7ce6b3b0-de82-46a3-a49a-8c751002268d\",\r\n    \"ipConfigurations\": [\r\n      {\r\n        \"name\": \"Nic-IP-config\",\r\n        \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796/ipConfigurations/Nic-IP-config\",\r\n        \"etag\": \"W/\\\"2d8db33a-1a2a-4248-8733-761f96f9ea19\\\"\",\r\n        \"properties\": {\r\n          \"provisioningState\": \"Succeeded\",\r\n          \"privateIPAddress\": \"10.0.0.4\",\r\n          \"privateIPAllocationMethod\": \"Dynamic\",\r\n          \"subnet\": {\r\n            \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\"\r\n          },\r\n          \"primary\": true\r\n        }\r\n      }\r\n    ],\r\n    \"dnsSettings\": {\r\n      \"dnsServers\": [],\r\n      \"appliedDnsServers\": []\r\n    },\r\n    \"enableIPForwarding\": false\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1377',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '88cba854-4a23-43f5-bd77-1e186e7c049d',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/88cba854-4a23-43f5-bd77-1e186e7c049d?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1187',
  'x-ms-correlation-request-id': '76683f24-ebb2-4a85-87a3-e3ef618cdc72',
  'x-ms-routing-request-id': 'WESTUS:20160204T171432Z:76683f24-ebb2-4a85-87a3-e3ef618cdc72',
  date: 'Thu, 04 Feb 2016 17:14:32 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.put('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796?api-version=2015-06-15', '*')
  .reply(201, "{\r\n  \"name\": \"xplattestnic3796\",\r\n  \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796\",\r\n  \"etag\": \"W/\\\"2d8db33a-1a2a-4248-8733-761f96f9ea19\\\"\",\r\n  \"type\": \"Microsoft.Network/networkInterfaces\",\r\n  \"location\": \"southeastasia\",\r\n  \"properties\": {\r\n    \"provisioningState\": \"Succeeded\",\r\n    \"resourceGuid\": \"7ce6b3b0-de82-46a3-a49a-8c751002268d\",\r\n    \"ipConfigurations\": [\r\n      {\r\n        \"name\": \"Nic-IP-config\",\r\n        \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/networkInterfaces/xplattestnic3796/ipConfigurations/Nic-IP-config\",\r\n        \"etag\": \"W/\\\"2d8db33a-1a2a-4248-8733-761f96f9ea19\\\"\",\r\n        \"properties\": {\r\n          \"provisioningState\": \"Succeeded\",\r\n          \"privateIPAddress\": \"10.0.0.4\",\r\n          \"privateIPAllocationMethod\": \"Dynamic\",\r\n          \"subnet\": {\r\n            \"id\": \"/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTstVmssGCreate7800/providers/Microsoft.Network/virtualNetworks/xplattestvnet5443/subnets/xplattestsubnet3005\"\r\n          },\r\n          \"primary\": true\r\n        }\r\n      }\r\n    ],\r\n    \"dnsSettings\": {\r\n      \"dnsServers\": [],\r\n      \"appliedDnsServers\": []\r\n    },\r\n    \"enableIPForwarding\": false\r\n  }\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '1377',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-request-id': '88cba854-4a23-43f5-bd77-1e186e7c049d',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Network/locations/southeastasia/operations/88cba854-4a23-43f5-bd77-1e186e7c049d?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1187',
  'x-ms-correlation-request-id': '76683f24-ebb2-4a85-87a3-e3ef618cdc72',
  'x-ms-routing-request-id': 'WESTUS:20160204T171432Z:76683f24-ebb2-4a85-87a3-e3ef618cdc72',
  date: 'Thu, 04 Feb 2016 17:14:32 GMT',
  connection: 'close' });
 return result; }]];