// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate9801/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss/manualupgrade?api-version=2015-06-15', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917730403641735',
  'x-ms-request-id': '5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '508abbc3-ff76-4a78-bea6-902375c405c3',
  'x-ms-routing-request-id': 'WESTUS:20151204T000058Z:508abbc3-ff76-4a78-bea6-902375c405c3',
  date: 'Fri, 04 Dec 2015 00:00:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .filteringRequestBody(function (path) { return '*';})
.post('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate9801/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss/manualupgrade?api-version=2015-06-15', '*')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917730403641735',
  'x-ms-request-id': '5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1197',
  'x-ms-correlation-request-id': '508abbc3-ff76-4a78-bea6-902375c405c3',
  'x-ms-routing-request-id': 'WESTUS:20151204T000058Z:508abbc3-ff76-4a78-bea6-902375c405c3',
  date: 'Fri, 04 Dec 2015 00:00:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2015-12-04T00:00:59.1558705+00:00\",\r\n  \"endTime\": \"2015-12-04T00:00:59.9370822+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917730403641735',
  'x-ms-request-id': '5b0ca5e7-2ab3-4b04-ae6a-6e0af0ce3dd7',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14989',
  'x-ms-correlation-request-id': '282cbca2-d492-4946-830a-4423994bfdc6',
  'x-ms-routing-request-id': 'WESTUS:20151204T000129Z:282cbca2-d492-4946-830a-4423994bfdc6',
  date: 'Fri, 04 Dec 2015 00:01:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"5c50af8b-3ad4-4fe5-9da5-45467d4a9b4a\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2015-12-04T00:00:59.1558705+00:00\",\r\n  \"endTime\": \"2015-12-04T00:00:59.9370822+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917730403641735',
  'x-ms-request-id': '5b0ca5e7-2ab3-4b04-ae6a-6e0af0ce3dd7',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14989',
  'x-ms-correlation-request-id': '282cbca2-d492-4946-830a-4423994bfdc6',
  'x-ms-routing-request-id': 'WESTUS:20151204T000129Z:282cbca2-d492-4946-830a-4423994bfdc6',
  date: 'Fri, 04 Dec 2015 00:01:28 GMT',
  connection: 'close' });
 return result; }]];