// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate5418/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': 'ee7cae55-f806-44d2-9a65-eecad4cfff9d',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1189',
  'x-ms-correlation-request-id': 'a8965f17-948a-447b-a2c3-9c9ddd0f0f6b',
  'x-ms-routing-request-id': 'WESTUS:20151130T232010Z:a8965f17-948a-447b-a2c3-9c9ddd0f0f6b',
  date: 'Mon, 30 Nov 2015 23:20:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate5418/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': 'ee7cae55-f806-44d2-9a65-eecad4cfff9d',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1189',
  'x-ms-correlation-request-id': 'a8965f17-948a-447b-a2c3-9c9ddd0f0f6b',
  'x-ms-routing-request-id': 'WESTUS:20151130T232010Z:a8965f17-948a-447b-a2c3-9c9ddd0f0f6b',
  date: 'Mon, 30 Nov 2015 23:20:10 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': 'e1b5c550-f8c2-4680-b654-90c3e62b1d81',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14980',
  'x-ms-correlation-request-id': '7dfb0206-0e9d-4f0d-ac0e-c919002d0512',
  'x-ms-routing-request-id': 'WESTUS:20151130T232041Z:7dfb0206-0e9d-4f0d-ac0e-c919002d0512',
  date: 'Mon, 30 Nov 2015 23:20:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': 'e1b5c550-f8c2-4680-b654-90c3e62b1d81',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14980',
  'x-ms-correlation-request-id': '7dfb0206-0e9d-4f0d-ac0e-c919002d0512',
  'x-ms-routing-request-id': 'WESTUS:20151130T232041Z:7dfb0206-0e9d-4f0d-ac0e-c919002d0512',
  date: 'Mon, 30 Nov 2015 23:20:40 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': 'f6540771-62f2-447a-bad5-ab6f86c7fbd7',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14953',
  'x-ms-correlation-request-id': '5cc4e39e-aefc-439e-bcbb-3b6d9d8c9a85',
  'x-ms-routing-request-id': 'WESTUS:20151130T232112Z:5cc4e39e-aefc-439e-bcbb-3b6d9d8c9a85',
  date: 'Mon, 30 Nov 2015 23:21:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': 'f6540771-62f2-447a-bad5-ab6f86c7fbd7',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14953',
  'x-ms-correlation-request-id': '5cc4e39e-aefc-439e-bcbb-3b6d9d8c9a85',
  'x-ms-routing-request-id': 'WESTUS:20151130T232112Z:5cc4e39e-aefc-439e-bcbb-3b6d9d8c9a85',
  date: 'Mon, 30 Nov 2015 23:21:12 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': '7ff30ab6-d813-4c7a-9bbe-a4ea896102bc',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14973',
  'x-ms-correlation-request-id': 'c9925c3d-2252-45e2-9de8-813c57a98d8e',
  'x-ms-routing-request-id': 'WESTUS:20151130T232143Z:c9925c3d-2252-45e2-9de8-813c57a98d8e',
  date: 'Mon, 30 Nov 2015 23:21:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': '7ff30ab6-d813-4c7a-9bbe-a4ea896102bc',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14973',
  'x-ms-correlation-request-id': 'c9925c3d-2252-45e2-9de8-813c57a98d8e',
  'x-ms-routing-request-id': 'WESTUS:20151130T232143Z:c9925c3d-2252-45e2-9de8-813c57a98d8e',
  date: 'Mon, 30 Nov 2015 23:21:43 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\",\r\n  \"endTime\": \"2015-11-30T23:22:02.3257748+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': '6810b663-4862-497d-99af-a0cd637a66c1',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14972',
  'x-ms-correlation-request-id': '0b64c0b3-527d-4c92-b587-ce87f41eeb24',
  'x-ms-routing-request-id': 'WESTUS:20151130T232214Z:0b64c0b3-527d-4c92-b587-ce87f41eeb24',
  date: 'Mon, 30 Nov 2015 23:22:14 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/ee7cae55-f806-44d2-9a65-eecad4cfff9d?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"ee7cae55-f806-44d2-9a65-eecad4cfff9d\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2015-11-30T23:20:08.9456013+00:00\",\r\n  \"endTime\": \"2015-11-30T23:22:02.3257748+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130917733709256791',
  'x-ms-request-id': '6810b663-4862-497d-99af-a0cd637a66c1',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14972',
  'x-ms-correlation-request-id': '0b64c0b3-527d-4c92-b587-ce87f41eeb24',
  'x-ms-routing-request-id': 'WESTUS:20151130T232214Z:0b64c0b3-527d-4c92-b587-ce87f41eeb24',
  date: 'Mon, 30 Nov 2015 23:22:14 GMT',
  connection: 'close' });
 return result; }]];