// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate5733/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss/instanceView?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/virtualMachineScaleSets/xplattestvmss' under resource group 'xplatTestVMSSCreate5733' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '27f8a6c2-d46a-4e3a-9b5a-690a6b0aaee6',
  'x-ms-correlation-request-id': '27f8a6c2-d46a-4e3a-9b5a-690a6b0aaee6',
  'x-ms-routing-request-id': 'CENTRALUS:20160202T004715Z:27f8a6c2-d46a-4e3a-9b5a-690a6b0aaee6',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 02 Feb 2016 00:47:14 GMT',
  connection: 'close',
  'content-length': '182' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate5733/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss/instanceView?api-version=2015-06-15')
  .reply(404, "{\"error\":{\"code\":\"ResourceNotFound\",\"message\":\"The Resource 'Microsoft.Compute/virtualMachineScaleSets/xplattestvmss' under resource group 'xplatTestVMSSCreate5733' was not found.\"}}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'x-ms-failure-cause': 'gateway',
  'x-ms-request-id': '27f8a6c2-d46a-4e3a-9b5a-690a6b0aaee6',
  'x-ms-correlation-request-id': '27f8a6c2-d46a-4e3a-9b5a-690a6b0aaee6',
  'x-ms-routing-request-id': 'CENTRALUS:20160202T004715Z:27f8a6c2-d46a-4e3a-9b5a-690a6b0aaee6',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  date: 'Tue, 02 Feb 2016 00:47:14 GMT',
  connection: 'close',
  'content-length': '182' });
 return result; }]];