// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    managementCertificate: {
      key: 'mockedKey',
      cert: 'mockedCert'
    },
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate53/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'e15d9e1f-0847-41be-bead-17f451877941',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': '449fe045-772e-4170-bdc1-8705926850a0',
  'x-ms-routing-request-id': 'WESTUS:20160223T005624Z:449fe045-772e-4170-bdc1-8705926850a0',
  date: 'Tue, 23 Feb 2016 00:56:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate53/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'e15d9e1f-0847-41be-bead-17f451877941',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': '449fe045-772e-4170-bdc1-8705926850a0',
  'x-ms-routing-request-id': 'WESTUS:20160223T005624Z:449fe045-772e-4170-bdc1-8705926850a0',
  date: 'Tue, 23 Feb 2016 00:56:23 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"e15d9e1f-0847-41be-bead-17f451877941\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:56:24.3543946+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '295cf9d8-f88a-459c-a80d-9d6568397503',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': 'dc01b5d4-54b6-4a35-85e9-6793fe03be61',
  'x-ms-routing-request-id': 'WESTUS:20160223T005655Z:dc01b5d4-54b6-4a35-85e9-6793fe03be61',
  date: 'Tue, 23 Feb 2016 00:56:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"e15d9e1f-0847-41be-bead-17f451877941\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:56:24.3543946+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '295cf9d8-f88a-459c-a80d-9d6568397503',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': 'dc01b5d4-54b6-4a35-85e9-6793fe03be61',
  'x-ms-routing-request-id': 'WESTUS:20160223T005655Z:dc01b5d4-54b6-4a35-85e9-6793fe03be61',
  date: 'Tue, 23 Feb 2016 00:56:55 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"e15d9e1f-0847-41be-bead-17f451877941\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:56:24.3543946+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '992384e8-6ba5-4f6d-adb2-21e02da4570f',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '4bdbc46e-976b-4369-8f41-58bcc2016369',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005726Z:4bdbc46e-976b-4369-8f41-58bcc2016369',
  date: 'Tue, 23 Feb 2016 00:57:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"e15d9e1f-0847-41be-bead-17f451877941\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:56:24.3543946+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '992384e8-6ba5-4f6d-adb2-21e02da4570f',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14995',
  'x-ms-correlation-request-id': '4bdbc46e-976b-4369-8f41-58bcc2016369',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005726Z:4bdbc46e-976b-4369-8f41-58bcc2016369',
  date: 'Tue, 23 Feb 2016 00:57:26 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"e15d9e1f-0847-41be-bead-17f451877941\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2016-02-23T00:56:24.3543946+00:00\",\r\n  \"endTime\": \"2016-02-23T00:57:57.151342+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '190',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'b1eb7527-d4d4-4c46-b73e-5bbb53d43f74',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14991',
  'x-ms-correlation-request-id': 'e18074b2-4a86-42e3-b252-970661cc7880',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005758Z:e18074b2-4a86-42e3-b252-970661cc7880',
  date: 'Tue, 23 Feb 2016 00:57:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/e15d9e1f-0847-41be-bead-17f451877941?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"e15d9e1f-0847-41be-bead-17f451877941\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2016-02-23T00:56:24.3543946+00:00\",\r\n  \"endTime\": \"2016-02-23T00:57:57.151342+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '190',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'b1eb7527-d4d4-4c46-b73e-5bbb53d43f74',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14991',
  'x-ms-correlation-request-id': 'e18074b2-4a86-42e3-b252-970661cc7880',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005758Z:e18074b2-4a86-42e3-b252-970661cc7880',
  date: 'Tue, 23 Feb 2016 00:57:58 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate53/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss1?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '37e8c12e-4459-4185-a76b-135f7cdab314',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'eb8db76e-ca63-4770-91d6-085eea9f3e4d',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005800Z:eb8db76e-ca63-4770-91d6-085eea9f3e4d',
  date: 'Tue, 23 Feb 2016 00:58:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate53/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvmss1?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '37e8c12e-4459-4185-a76b-135f7cdab314',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1198',
  'x-ms-correlation-request-id': 'eb8db76e-ca63-4770-91d6-085eea9f3e4d',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005800Z:eb8db76e-ca63-4770-91d6-085eea9f3e4d',
  date: 'Tue, 23 Feb 2016 00:58:00 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"37e8c12e-4459-4185-a76b-135f7cdab314\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:58:00.1982261+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'da9bfba1-3877-4279-b758-67451d29294a',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': 'f1e512fb-109f-401d-89ce-1c8d8fc57c6b',
  'x-ms-routing-request-id': 'WESTUS:20160223T005831Z:f1e512fb-109f-401d-89ce-1c8d8fc57c6b',
  date: 'Tue, 23 Feb 2016 00:58:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"37e8c12e-4459-4185-a76b-135f7cdab314\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:58:00.1982261+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'da9bfba1-3877-4279-b758-67451d29294a',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': 'f1e512fb-109f-401d-89ce-1c8d8fc57c6b',
  'x-ms-routing-request-id': 'WESTUS:20160223T005831Z:f1e512fb-109f-401d-89ce-1c8d8fc57c6b',
  date: 'Tue, 23 Feb 2016 00:58:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"37e8c12e-4459-4185-a76b-135f7cdab314\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:58:00.1982261+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '7f292885-b226-4714-9a7d-55c4ac05c7f3',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': '8a1b4cc2-0abc-4983-9355-f5081c9ba055',
  'x-ms-routing-request-id': 'WESTUS:20160223T005902Z:8a1b4cc2-0abc-4983-9355-f5081c9ba055',
  date: 'Tue, 23 Feb 2016 00:59:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"37e8c12e-4459-4185-a76b-135f7cdab314\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-23T00:58:00.1982261+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '7f292885-b226-4714-9a7d-55c4ac05c7f3',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14993',
  'x-ms-correlation-request-id': '8a1b4cc2-0abc-4983-9355-f5081c9ba055',
  'x-ms-routing-request-id': 'WESTUS:20160223T005902Z:8a1b4cc2-0abc-4983-9355-f5081c9ba055',
  date: 'Tue, 23 Feb 2016 00:59:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"37e8c12e-4459-4185-a76b-135f7cdab314\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2016-02-23T00:58:00.1982261+00:00\",\r\n  \"endTime\": \"2016-02-23T00:59:32.9794635+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '4c4c839f-45fc-4823-8eff-58aa89729bb1',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14994',
  'x-ms-correlation-request-id': '136ec179-3dd2-4170-9306-59606eedf1c8',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005934Z:136ec179-3dd2-4170-9306-59606eedf1c8',
  date: 'Tue, 23 Feb 2016 00:59:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/37e8c12e-4459-4185-a76b-135f7cdab314?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"37e8c12e-4459-4185-a76b-135f7cdab314\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2016-02-23T00:58:00.1982261+00:00\",\r\n  \"endTime\": \"2016-02-23T00:59:32.9794635+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '191',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '4c4c839f-45fc-4823-8eff-58aa89729bb1',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14994',
  'x-ms-correlation-request-id': '136ec179-3dd2-4170-9306-59606eedf1c8',
  'x-ms-routing-request-id': 'CENTRALUS:20160223T005934Z:136ec179-3dd2-4170-9306-59606eedf1c8',
  date: 'Tue, 23 Feb 2016 00:59:33 GMT',
  connection: 'close' });
 return result; }]];