// This file has been autogenerated.

var profile = require('../../../lib/util/profile');

exports.getMockedProfile = function () {
  var newProfile = new profile.Profile();

  newProfile.addSubscription(new profile.Subscription({
    id: 'e33f361b-53c2-4cc7-b829-78906708387b',
    name: 'Microsoft Azure Internal Consumption',
    user: {
      name: 'user@domain.example',
      type: 'servicePrincipal'
    },
    tenantId: '72f988bf-86f1-41af-91ab-2d7cd011db47',
    state: 'Enabled',
    registeredProviders: [],
    isDefault: true
  }, newProfile.environments['AzureCloud']));

  return newProfile;
};

exports.setEnvironment = function() {
  process.env['AZURE_VM_TEST_LOCATION'] = 'southeastasia';
  process.env['SSHCERT'] = 'test/myCert.pem';
};

exports.scopes = [[function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate589/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvms2?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '2628cdbc-12ee-4217-824b-e847a52b2df7',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '2d340abb-7756-4778-9163-a72a944ee948',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T232758Z:2d340abb-7756-4778-9163-a72a944ee948',
  date: 'Mon, 01 Feb 2016 23:27:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .delete('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/resourceGroups/xplatTestVMSSCreate589/providers/Microsoft.Compute/virtualMachineScaleSets/xplattestvms2?api-version=2015-06-15')
  .reply(202, "", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '0',
  expires: '-1',
  location: 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?monitor=true&api-version=2015-06-15',
  'azure-asyncoperation': 'https://management.azure.com/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '2628cdbc-12ee-4217-824b-e847a52b2df7',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-writes': '1194',
  'x-ms-correlation-request-id': '2d340abb-7756-4778-9163-a72a944ee948',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T232758Z:2d340abb-7756-4778-9163-a72a944ee948',
  date: 'Mon, 01 Feb 2016 23:27:57 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '44cea2dd-68d7-494d-9568-e5afa1fc2433',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14928',
  'x-ms-correlation-request-id': '77389b6e-358f-437e-a45b-847df97d49ad',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T232829Z:77389b6e-358f-437e-a45b-847df97d49ad',
  date: 'Mon, 01 Feb 2016 23:28:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '44cea2dd-68d7-494d-9568-e5afa1fc2433',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14928',
  'x-ms-correlation-request-id': '77389b6e-358f-437e-a45b-847df97d49ad',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T232829Z:77389b6e-358f-437e-a45b-847df97d49ad',
  date: 'Mon, 01 Feb 2016 23:28:28 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '3f0c2343-1b78-4a54-98de-9972916d3689',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14989',
  'x-ms-correlation-request-id': '394aa7f3-239a-4e6d-a3c2-0dfd3cedf735',
  'x-ms-routing-request-id': 'WESTUS:20160201T232900Z:394aa7f3-239a-4e6d-a3c2-0dfd3cedf735',
  date: 'Mon, 01 Feb 2016 23:28:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '3f0c2343-1b78-4a54-98de-9972916d3689',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14989',
  'x-ms-correlation-request-id': '394aa7f3-239a-4e6d-a3c2-0dfd3cedf735',
  'x-ms-routing-request-id': 'WESTUS:20160201T232900Z:394aa7f3-239a-4e6d-a3c2-0dfd3cedf735',
  date: 'Mon, 01 Feb 2016 23:28:59 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'b084e452-4d06-451d-99ce-4203b867c0fb',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14990',
  'x-ms-correlation-request-id': '0ac04204-5521-489f-aa80-4d4cd4c1dd8a',
  'x-ms-routing-request-id': 'WESTUS:20160201T232931Z:0ac04204-5521-489f-aa80-4d4cd4c1dd8a',
  date: 'Mon, 01 Feb 2016 23:29:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': 'b084e452-4d06-451d-99ce-4203b867c0fb',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14990',
  'x-ms-correlation-request-id': '0ac04204-5521-489f-aa80-4d4cd4c1dd8a',
  'x-ms-routing-request-id': 'WESTUS:20160201T232931Z:0ac04204-5521-489f-aa80-4d4cd4c1dd8a',
  date: 'Mon, 01 Feb 2016 23:29:30 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '4d06cdc2-d592-4dcb-8a8f-f973276fcfcd',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14978',
  'x-ms-correlation-request-id': '5a659285-c684-433b-bb1c-8eb1cdc74353',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T233002Z:5a659285-c684-433b-bb1c-8eb1cdc74353',
  date: 'Mon, 01 Feb 2016 23:30:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"InProgress\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '141',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '4d06cdc2-d592-4dcb-8a8f-f973276fcfcd',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14978',
  'x-ms-correlation-request-id': '5a659285-c684-433b-bb1c-8eb1cdc74353',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T233002Z:5a659285-c684-433b-bb1c-8eb1cdc74353',
  date: 'Mon, 01 Feb 2016 23:30:01 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('http://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\",\r\n  \"endTime\": \"2016-02-01T23:30:21.083491+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '190',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '31fd97cd-9d52-4bae-b418-13409c940170',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14977',
  'x-ms-correlation-request-id': '3470efe5-027c-4c3f-b6b5-09dc28b96d90',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T233033Z:3470efe5-027c-4c3f-b6b5-09dc28b96d90',
  date: 'Mon, 01 Feb 2016 23:30:33 GMT',
  connection: 'close' });
 return result; },
function (nock) { 
var result = 
nock('https://management.azure.com:443')
  .get('/subscriptions/e33f361b-53c2-4cc7-b829-78906708387b/providers/Microsoft.Compute/locations/southeastasia/operations/2628cdbc-12ee-4217-824b-e847a52b2df7?api-version=2015-06-15')
  .reply(200, "{\r\n  \"operationId\": \"2628cdbc-12ee-4217-824b-e847a52b2df7\",\r\n  \"status\": \"Succeeded\",\r\n  \"startTime\": \"2016-02-01T23:27:57.4272431+00:00\",\r\n  \"endTime\": \"2016-02-01T23:30:21.083491+00:00\"\r\n}", { 'cache-control': 'no-cache',
  pragma: 'no-cache',
  'content-length': '190',
  'content-type': 'application/json; charset=utf-8',
  expires: '-1',
  'strict-transport-security': 'max-age=31536000; includeSubDomains',
  'x-ms-served-by': 'dce02487-9cda-4782-8138-773eb1573792_130923832742225921',
  'x-ms-request-id': '31fd97cd-9d52-4bae-b418-13409c940170',
  server: 'Microsoft-HTTPAPI/2.0, Microsoft-HTTPAPI/2.0',
  'x-ms-ratelimit-remaining-subscription-reads': '14977',
  'x-ms-correlation-request-id': '3470efe5-027c-4c3f-b6b5-09dc28b96d90',
  'x-ms-routing-request-id': 'CENTRALUS:20160201T233033Z:3470efe5-027c-4c3f-b6b5-09dc28b96d90',
  date: 'Mon, 01 Feb 2016 23:30:33 GMT',
  connection: 'close' });
 return result; }]];